#!/usr/bin/env dotnet
// Regenerates src/FFmpeg.Interop/Generated from pinned FFmpeg and SDK headers.
//
//   dotnet run generate/Generate.cs            all passes this host can run
//   dotnet run generate/Generate.cs -- --list  show the passes and which host runs each
//
// Windows runs every pass except VideoToolbox (the D3D11 pass needs the Windows SDK); macOS runs
// the VideoToolbox pass (it needs the macOS SDK). Each pass only rewrites its own output folder, so
// the two hosts produce disjoint files. The generated files are committed; consumers never run this.
//
// Prerequisites: the ClangSharpPInvokeGenerator local tool (dotnet tool restore) and an LLVM
// install whose clang major matches ClangMajor below. The libclang natives come from the packages
// referenced here. A libclang handed another major's builtin headers does not fail: it parses less
// and exits 0, which writes truncated bindings, so the major is checked rather than assumed.

#:package libclang.runtime.win-x64
#:package libclang.runtime.linux-x64
#:package libclang.runtime.osx-arm64
#:package libClangSharp.runtime.win-x64
#:package libClangSharp.runtime.linux-x64
#:package libClangSharp.runtime.osx-arm64
#:property PublishAot=false
#:property GenerateDocumentationFile=true
#:property NoWarn=$(NoWarn);CS1591

using System.Diagnostics;
using System.Formats.Tar;
using System.IO.Compression;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

const int ClangMajor = 22;
const string LibClangVersion = "22.1.8";
const string LibClangSharpVersion = "22.1.8.2";

string repoRoot = FindRepoRoot();
string generateDir = Path.Combine(repoRoot, "generate");
string cacheDir = Path.Combine(generateDir, ".cache");
string outputRoot = Path.Combine(repoRoot, "src", "FFmpeg.Interop", "Generated");
string testOutputRoot = Path.Combine(repoRoot, "tests", "FFmpeg.Interop.Tests", "Generated");

Host host =
    OperatingSystem.IsWindows() ? Host.Windows
    : OperatingSystem.IsMacOS() ? Host.MacOS
    : Host.Linux;
IReadOnlyList<Pass> passes = Passes.All;

if (args.Contains("--list"))
{
    foreach (Pass pass in passes)
    {
        Console.WriteLine($"{pass.Name, -16} {pass.Library, -12} runs on {pass.Host}");
    }

    return 0;
}

JsonObject inputs = JsonNode
    .Parse(await File.ReadAllTextAsync(Path.Combine(generateDir, "inputs.json")))!
    .AsObject();
Dictionary<string, string> roots = [];
foreach ((string name, JsonNode? node) in inputs)
{
    string url = node!["url"]!.GetValue<string>();
    string sha256 = node["sha256"]!.GetValue<string>();
    roots[name] = await FetchAndExtractAsync(name, url, sha256);
}

string ffmpegInclude = PrepareFFmpegInclude(
    roots["ffmpeg"],
    inputs["ffmpeg"]!["version"]!.GetValue<string>()
);
string vaInclude = PrepareLibVaInclude(roots["libva"]);
string vulkanInclude = Path.Combine(roots["vulkan"], "include");
string nvInclude = Path.Combine(roots["nvcodec"], "include");
Dictionary<string, string> includeRoots = new()
{
    ["ffmpeg"] = ffmpegInclude,
    ["libva"] = vaInclude,
    ["vulkan"] = vulkanInclude,
    ["nvcodec"] = nvInclude,
};

string resourceDir = FindClangResourceDirectory();
string nativeDir = LibClangNativeDirectories();

// Prefixed to every generated file by the generator. The native declarations carry no XML
// documentation; FFmpeg's own header comments are the reference until the generator imports them.
string headerFile = Path.Combine(cacheDir, "header.txt");
await File.WriteAllTextAsync(
    headerFile,
    "// <auto-generated/>\n// Generated by generate/Generate.cs from pinned FFmpeg headers. Do not edit.\n\n"
        + "#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member\n"
);
int failures = 0;

foreach (Pass pass in passes)
{
    if (pass.Host != host)
    {
        Console.WriteLine($"skip  {pass.Name} (runs on {pass.Host})");
        continue;
    }

    Console.WriteLine($"run   {pass.Name}");
    if (!await RunPassAsync(pass))
    {
        failures++;
    }
}

if (failures == 0)
{
    DeduplicateForwardDeclarations();
}

return failures == 0 ? 0 : 1;

// A struct a header only forward-declares comes out as an empty partial struct, once for every pass
// whose headers mention it. Those are opaque handles: one declaration is kept, the full definition
// when some pass has it, and none of them gets a layout test, because an empty C# struct has size 1
// and the C type has no size at all.
void DeduplicateForwardDeclarations()
{
    string[] passOrder = [.. passes.Select(static p => p.Name)];
    var declarations = Directory
        .EnumerateFiles(outputRoot, "*.g.cs", SearchOption.AllDirectories)
        .Select(f =>
            (
                File: f,
                Pass: Path.GetFileName(Path.GetDirectoryName(f))!,
                Type: Path.GetFileName(f)[..^".g.cs".Length]
            )
        )
        .Where(static d => d.Pass != "helpers")
        .GroupBy(static d => d.Type);

    int removed = 0;
    foreach (var group in declarations)
    {
        var ordered = group
            .OrderBy(d => IsOpaque(d.File) ? 1 : 0)
            .ThenBy(d => Array.IndexOf(passOrder, d.Pass))
            .ToList();
        foreach (var duplicate in ordered.Skip(1))
        {
            File.Delete(duplicate.File);
            DeleteTest(duplicate.Pass, duplicate.Type);
            removed++;
        }
    }

    // Opaque structs also appear nested in the type that points at them (AVCodecContext.AVCodecInternal),
    // so their tests are removed by name from wherever the generator put them.
    HashSet<string> opaque =
    [
        .. Directory
            .EnumerateFiles(outputRoot, "*.g.cs", SearchOption.AllDirectories)
            .SelectMany(static f => OpaqueStruct().Matches(File.ReadAllText(f)))
            .Select(static m => m.Groups[1].Value),
    ];
    int opaqueTests = 0;
    foreach (
        string test in Directory.EnumerateFiles(
            testOutputRoot,
            "*.g.cs",
            SearchOption.AllDirectories
        )
    )
    {
        string text = File.ReadAllText(test);
        string kept = StripOpaque(text);
        if (kept == text)
        {
            continue;
        }

        opaqueTests += TestClass().Matches(text).Count - TestClass().Matches(kept).Count;
        if (kept.Contains(" class ", StringComparison.Ordinal))
        {
            File.WriteAllText(test, kept, new UTF8Encoding(false));
        }
        else
        {
            File.Delete(test);
        }
    }

    Console.WriteLine(
        $"ok    {removed} duplicate forward declarations removed, {opaqueTests} opaque-struct tests dropped"
    );

    // A kept class can hold nested ones, which the outer match has already consumed, so the search
    // continues inside it after its summary line.
    string StripOpaque(string text) =>
        TestClass()
            .Replace(
                text,
                m =>
                {
                    if (opaque.Contains(m.Groups["name"].Value))
                    {
                        return string.Empty;
                    }

                    int body = m.Value.IndexOf('\n', StringComparison.Ordinal) + 1;
                    return m.Value[..body] + StripOpaque(m.Value[body..]);
                }
            );

    void DeleteTest(string pass, string type)
    {
        string test = Path.Combine(testOutputRoot, pass, type + "Tests.g.cs");
        if (File.Exists(test))
        {
            File.Delete(test);
        }
    }
}

static bool IsOpaque(string file) =>
    !OpaqueStruct()
        .Replace(File.ReadAllText(file), string.Empty)
        .Contains(" struct ", StringComparison.Ordinal);

async Task<bool> RunPassAsync(Pass pass)
{
    string work = Path.Combine(cacheDir, "work", pass.Name);
    Directory.CreateDirectory(work);
    string composite = Path.Combine(work, $"{pass.Name}_composite.h");
    await File.WriteAllLinesAsync(composite, pass.Includes.Select(static h => $"#include <{h}>"));

    string rawOut = Path.Combine(work, "out");
    string rawTests = Path.Combine(work, "tests");

    // Macros that alias an enum member (AV_PIX_FMT_RGB32 -> AV_PIX_FMT_BGRA) come out as int
    // constants, which C# will not initialise from an enum. The generator only types a macro through
    // an exact --with-type name, so the first run discovers them and a second run types them.
    Dictionary<string, string> aliasTypes = [];
    for (int attempt = 0; ; attempt++)
    {
        DeleteDirectory(rawOut);
        DeleteDirectory(rawTests);
        string rspPath = Path.Combine(work, $"{pass.Name}.rsp");
        await File.WriteAllLinesAsync(rspPath, BuildResponseFile(pass, aliasTypes));

        (int exitCode, string log) = await RunToolAsync(
            $"@{rspPath}",
            "--file",
            composite,
            "--resource-directory",
            resourceDir,
            "--output",
            rawOut,
            "--test-output",
            rawTests
        );
        await File.WriteAllTextAsync(Path.Combine(work, "generator.log"), log);

        // The generator's exit code is the number of diagnostics it reported, allowed ones included,
        // so it is only a failure when negative. The diagnostics themselves decide.
        List<string> unexpected = [.. Diagnostics(log).Where(d => !Passes.IsAllowedDiagnostic(d))];
        if (exitCode < 0 || unexpected.Count > 0)
        {
            Console.WriteLine(
                $"FAIL  {pass.Name}: exit {exitCode}, {unexpected.Count} unexpected diagnostic(s)"
            );
            foreach (string diagnostic in unexpected.Take(40))
            {
                Console.WriteLine($"      {diagnostic}");
            }

            return false;
        }

        Dictionary<string, string> discovered = FindEnumAliasConstants(rawOut);
        if (discovered.Count == 0)
        {
            break;
        }

        if (attempt > 0)
        {
            Console.WriteLine(
                $"FAIL  {pass.Name}: enum-alias macros still untyped: {string.Join(", ", discovered.Keys.Take(10))}"
            );
            return false;
        }

        aliasTypes = discovered;
    }

    int files = Publish(rawOut, Path.Combine(outputRoot, pass.Name), static text => text);
    // The layout tests hard-code the sizes clang computed for this host. A struct holding a C long is
    // sized per OS (32-bit on Windows, 64-bit elsewhere), so its generated size test is only right on
    // one of them; those structs are covered by hand-written per-OS tests instead.
    HashSet<string> platformSized =
    [
        .. Directory
            .EnumerateFiles(rawOut, "*.cs")
            .Where(static f => File.ReadAllText(f).Contains("CULong", StringComparison.Ordinal))
            .Select(static f => Path.GetFileNameWithoutExtension(f) + "Tests"),
    ];
    foreach (string skipped in platformSized)
    {
        File.Delete(Path.Combine(rawTests, skipped + ".cs"));
    }

    int tests = Publish(rawTests, Path.Combine(testOutputRoot, pass.Name), XunitToMSTest);
    Console.WriteLine(
        $"ok    {pass.Name}: {files} files, {tests} layout tests, {aliasTypes.Count} enum-typed macros"
    );
    return true;
}

List<string> BuildResponseFile(Pass pass, Dictionary<string, string> aliasTypes)
{
    List<string> rsp =
    [
        "--config",
        "file=multi",
        "codegen=preview",
        // funcs-with-body=false: the headers' static inline functions are hand-written in
        // src/FFmpeg.Interop instead of machine-translated from C (C truthiness and implicit integer
        // conversions do not translate faithfully).
        "--generate",
        "macro-bindings",
        "tests-xunit",
        "file-scoped-namespaces",
        "empty-records",
        "funcs-with-body=false",
        "aggressive-inlining",
        $"disable-runtime-marshalling={pass.EmitsHelpers.ToString().ToLowerInvariant()}",
        $"helper-types={pass.EmitsHelpers.ToString().ToLowerInvariant()}",
        "--log",
        "exclusions",
        "--header-file",
        headerFile,
        "--namespace",
        "FFmpeg.Interop.Native",
        "--method-class-name",
        pass.ClassName,
        "--library-path",
        pass.Library,
        "--language",
        "c",
        "--std",
        "c11",
    ];
    foreach (string root in pass.IncludeRoots.Prepend("ffmpeg").Distinct())
    {
        rsp.Add("--include-directory");
        rsp.Add(ToForwardSlashes(includeRoots[root]));
    }

    // Anonymous-type descriptions in NativeTypeName carry the header path; strip the local cache
    // prefix so the committed output is the same on every machine.
    foreach (string root in includeRoots.Values)
    {
        rsp.Add("--native-type-names-to-strip");
        rsp.Add(ToForwardSlashes(root) + "/");
    }

    foreach (string header in pass.Traverse)
    {
        string[] parts = header.Split(':');
        rsp.Add("--traverse");
        rsp.Add(ToForwardSlashes(Path.Combine(includeRoots[parts[0]], parts[1])));
    }

    foreach (string remap in Passes.CommonRemaps.Concat(pass.Remaps))
    {
        rsp.Add("--remap");
        rsp.Add(remap);
    }

    foreach (
        (string macro, string enumType) in aliasTypes.OrderBy(
            static a => a.Key,
            StringComparer.Ordinal
        )
    )
    {
        rsp.Add("--with-type");
        rsp.Add($"{macro}={enumType}");
    }

    foreach (string include in pass.DeclarationFilter)
    {
        rsp.Add("--include");
        rsp.Add(include);
    }

    foreach (string ns in pass.Namespaces)
    {
        rsp.Add("--with-namespace");
        rsp.Add(ns);
    }

    foreach (string exclude in Passes.CommonExcludes.Concat(pass.Excludes))
    {
        rsp.Add("--exclude");
        rsp.Add(exclude);
    }

    foreach (string function in Passes.NoGCTransition)
    {
        rsp.Add("--with-suppressgctransition");
        rsp.Add(function);
    }

    return rsp;
}

// Every generated enum member (this pass and earlier ones), then every "const int X = Y;" whose Y is
// one of them.
Dictionary<string, string> FindEnumAliasConstants(string rawOut)
{
    Dictionary<string, string> memberToEnum = new(StringComparer.Ordinal);
    IEnumerable<string> sources = Directory
        .EnumerateFiles(rawOut, "*.cs")
        .Concat(
            Directory.Exists(outputRoot)
                ? Directory.EnumerateFiles(outputRoot, "*.g.cs", SearchOption.AllDirectories)
                : []
        );
    foreach (string file in sources)
    {
        string text = File.ReadAllText(file);
        foreach (Match enumMatch in Regex.Matches(text, @"public enum (\w+)[^{]*\{([^}]*)\}"))
        {
            foreach (
                Match member in Regex.Matches(
                    enumMatch.Groups[2].Value,
                    @"^\s+([A-Za-z_]\w*)\s*[=,\r\n]",
                    RegexOptions.Multiline
                )
            )
            {
                memberToEnum.TryAdd(member.Groups[1].Value, enumMatch.Groups[1].Value);
            }
        }
    }

    Dictionary<string, string> aliases = new(StringComparer.Ordinal);
    foreach (string file in Directory.EnumerateFiles(rawOut, "*.cs"))
    {
        foreach (
            Match constant in Regex.Matches(
                File.ReadAllText(file),
                @"public const int (\w+) = (\w+);"
            )
        )
        {
            if (memberToEnum.TryGetValue(constant.Groups[2].Value, out string? enumType))
            {
                aliases[constant.Groups[1].Value] = enumType;
            }
        }
    }

    return aliases;
}

async Task<(int ExitCode, string Log)> RunToolAsync(params string[] toolArgs)
{
    ProcessStartInfo start = new("dotnet")
    {
        RedirectStandardOutput = true,
        RedirectStandardError = true,
        WorkingDirectory = repoRoot,
    };
    start.ArgumentList.Add("tool");
    start.ArgumentList.Add("run");
    start.ArgumentList.Add("ClangSharpPInvokeGenerator");
    start.ArgumentList.Add("--");
    foreach (string arg in toolArgs)
    {
        start.ArgumentList.Add(arg);
    }

    string pathVariable = host switch
    {
        Host.Windows => "PATH",
        Host.MacOS => "DYLD_LIBRARY_PATH",
        _ => "LD_LIBRARY_PATH",
    };
    string existing = Environment.GetEnvironmentVariable(pathVariable) ?? string.Empty;
    start.Environment[pathVariable] = nativeDir + Path.PathSeparator + existing;

    using Process process =
        Process.Start(start)
        ?? throw new InvalidOperationException("Could not start the generator.");
    Task<string> stdout = process.StandardOutput.ReadToEndAsync();
    Task<string> stderr = process.StandardError.ReadToEndAsync();
    await process.WaitForExitAsync();
    return (process.ExitCode, await stdout + await stderr);
}

static IEnumerable<string> Diagnostics(string log) =>
    log.Split('\n')
        .Select(static l => l.Trim())
        .Where(static l =>
            l.StartsWith("Error", StringComparison.Ordinal)
            || l.StartsWith("Warning", StringComparison.Ordinal)
        );

int Publish(string from, string to, Func<string, string> transform)
{
    DeleteDirectory(to);
    if (!Directory.Exists(from))
    {
        return 0;
    }

    Directory.CreateDirectory(to);
    int count = 0;
    foreach (string file in Directory.EnumerateFiles(from, "*.cs"))
    {
        string text = transform(
            File.ReadAllText(file).Replace("\r\n", "\n", StringComparison.Ordinal)
        );
        File.WriteAllText(
            Path.Combine(to, Path.GetFileNameWithoutExtension(file) + ".g.cs"),
            text,
            new UTF8Encoding(false)
        );
        count++;
    }

    return count;
}

// The generator writes its layout tests for xUnit or NUnit only; the repository tests with MSTest. The
// generated tests use a fixed, small vocabulary (Fact, Assert.Equal, Assert.True, static test classes),
// so the translation is a set of exact substitutions, and anything outside it fails the build.
static string XunitToMSTest(string text) =>
    text.Replace("using Xunit;\n", string.Empty, StringComparison.Ordinal)
        .Replace(
            "namespace FFmpeg.Interop.Native.UnitTests;",
            "namespace FFmpeg.Interop.Native.Tests;",
            StringComparison.Ordinal
        )
        .Replace(
            "public static unsafe partial class",
            "[TestClass]\npublic sealed unsafe partial class",
            StringComparison.Ordinal
        )
        .Replace("[Fact]", "[TestMethod]", StringComparison.Ordinal)
        .Replace("public static void", "public void", StringComparison.Ordinal)
        .Replace("Assert.Equal(", "Assert.AreEqual(", StringComparison.Ordinal)
        .Replace("Assert.True(", "Assert.IsTrue(", StringComparison.Ordinal);

async Task<string> FetchAndExtractAsync(string name, string url, string sha256)
{
    string dir = Path.Combine(cacheDir, name);
    string archive = Path.Combine(cacheDir, $"{name}.tar.gz");
    string marker = Path.Combine(dir, ".sha256");
    if (File.Exists(marker) && (await File.ReadAllTextAsync(marker)).Trim() == sha256)
    {
        return SingleSubdirectory(dir);
    }

    Directory.CreateDirectory(cacheDir);
    using (HttpClient http = new())
    {
        await using Stream body = await http.GetStreamAsync(new Uri(url));
        await using FileStream file = File.Create(archive);
        await body.CopyToAsync(file);
    }

    string actual;
    await using (FileStream hashed = File.OpenRead(archive))
    {
        actual = Convert.ToHexStringLower(await SHA256.HashDataAsync(hashed));
    }

    if (!string.Equals(actual, sha256, StringComparison.OrdinalIgnoreCase))
    {
        throw new InvalidDataException(
            $"{name}: {url} hashed to {actual}, inputs.json pins {sha256}."
        );
    }

    DeleteDirectory(dir);
    Directory.CreateDirectory(dir);
    await using (FileStream file = File.OpenRead(archive))
    await using (GZipStream gzip = new(file, CompressionMode.Decompress))
    {
        await TarFile.ExtractToDirectoryAsync(gzip, dir, overwriteFiles: true);
    }

    await File.WriteAllTextAsync(marker, sha256);
    File.Delete(archive);
    return SingleSubdirectory(dir);
}

// FFmpeg's public headers include libavutil/avconfig.h, which configure writes. Its two defines are
// fixed for every target these bindings serve (little-endian, fast unaligned access), so it is
// written here rather than pulled from a configured build tree.
static string PrepareFFmpegInclude(string sourceRoot, string version)
{
    File.WriteAllText(
        Path.Combine(sourceRoot, "libavutil", "avconfig.h"),
        $"/* Written by generate/Generate.cs for FFmpeg {version}; matches configure on little-endian targets. */\n"
            + "#ifndef AVUTIL_AVCONFIG_H\n#define AVUTIL_AVCONFIG_H\n#define AV_HAVE_BIGENDIAN 0\n#define AV_HAVE_FAST_UNALIGNED 1\n#endif\n"
    );
    return sourceRoot;
}

// va.h includes va_version.h, which meson writes from va_version.h.in using the API version in
// meson.build. Reproduce that substitution from the pinned sources.
static string PrepareLibVaInclude(string sourceRoot)
{
    string meson = File.ReadAllText(Path.Combine(sourceRoot, "meson.build"));
    string Part(string key) => Regex.Match(meson, $@"{key}\s*=\s*(\d+)").Groups[1].Value;
    string major = Part("va_api_major_version");
    string minor = Part("va_api_minor_version");
    string micro = Part("va_api_micro_version");
    string template = File.ReadAllText(Path.Combine(sourceRoot, "va", "va_version.h.in"));
    string header = template
        .Replace("@VA_API_MAJOR_VERSION@", major, StringComparison.Ordinal)
        .Replace("@VA_API_MINOR_VERSION@", minor, StringComparison.Ordinal)
        .Replace("@VA_API_MICRO_VERSION@", micro, StringComparison.Ordinal)
        .Replace("@VA_API_VERSION@", $"{major}.{minor}.{micro}", StringComparison.Ordinal);
    File.WriteAllText(Path.Combine(sourceRoot, "va", "va_version.h"), header);
    return sourceRoot;
}

string FindClangResourceDirectory()
{
    string[] candidates = host switch
    {
        Host.Windows => [$@"C:\Program Files\LLVM\lib\clang\{ClangMajor}"],
        Host.MacOS =>
        [
            $"/opt/homebrew/opt/llvm@{ClangMajor}/lib/clang/{ClangMajor}",
            $"/opt/homebrew/opt/llvm/lib/clang/{ClangMajor}",
        ],
        _ => [$"/usr/lib/llvm-{ClangMajor}/lib/clang/{ClangMajor}", $"/usr/lib/clang/{ClangMajor}"],
    };
    return candidates.FirstOrDefault(static c =>
            File.Exists(Path.Combine(c, "include", "stddef.h"))
        )
        ?? throw new InvalidOperationException(
            $"No clang {ClangMajor} resource directory found. Install LLVM {ClangMajor}; libclang {LibClangVersion} handed another major's builtin headers parses less and still exits 0."
        );
}

string LibClangNativeDirectories()
{
    string packages =
        Environment.GetEnvironmentVariable("NUGET_PACKAGES")
        ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".nuget",
            "packages"
        );
    string rid = RuntimeInformation.RuntimeIdentifier;
    string clang = Path.Combine(
        packages,
        $"libclang.runtime.{rid}",
        LibClangVersion,
        "runtimes",
        rid,
        "native"
    );
    string clangSharp = Path.Combine(
        packages,
        $"libclangsharp.runtime.{rid}",
        LibClangSharpVersion,
        "runtimes",
        rid,
        "native"
    );
    return Directory.Exists(clang) && Directory.Exists(clangSharp)
        ? clang + Path.PathSeparator + clangSharp
        : throw new InvalidOperationException(
            $"libclang natives for {rid} were not restored under {packages}."
        );
}

static string SingleSubdirectory(string dir) =>
    Directory.GetDirectories(dir) is [string only]
        ? only
        : throw new InvalidDataException($"{dir} should hold one extracted root.");

static void DeleteDirectory(string dir)
{
    if (Directory.Exists(dir))
    {
        Directory.Delete(dir, recursive: true);
    }
}

static string ToForwardSlashes(string path) => path.Replace('\\', '/');

static string FindRepoRoot()
{
    DirectoryInfo? dir = new(AppContext.BaseDirectory);
    for (
        DirectoryInfo? current = new(Environment.CurrentDirectory);
        current is not null;
        current = current.Parent
    )
    {
        if (File.Exists(Path.Combine(current.FullName, "generate", "inputs.json")))
        {
            return current.FullName;
        }
    }

    throw new InvalidOperationException(
        $"Run from inside the repository (looked upward from {dir.FullName})."
    );
}

enum Host
{
    Windows,
    Linux,
    MacOS,
}

sealed record Pass(
    string Name,
    string Library,
    string ClassName,
    Host Host,
    string[] Includes,
    string[] Traverse,
    string[] IncludeRoots,
    string[] Remaps,
    string[] Excludes
)
{
    // Declaration-name allow list (--include); empty means everything traversed.
    public string[] DeclarationFilter { get; init; } = [];

    // Per-declaration namespaces (--with-namespace).
    public string[] Namespaces { get; init; } = [];

    // The assembly-wide attributes and helper types come from a pass of their own over an empty
    // header: with helper-types on, the generator writes no layout tests for that pass, so a real
    // library pass cannot also carry them.
    public bool EmitsHelpers => Name == "helpers";
}

static class Passes
{
    // va_list only ever crosses the boundary as a parameter, where every supported ABI passes a
    // pointer. unsigned long is 32-bit on Windows and 64-bit elsewhere; CULong carries that.
    // FILE only appears as FILE* in the dump helpers; callers pass a native C runtime FILE*, so it is
    // opaque here (_iobuf is its Windows spelling, _IO_FILE glibc's).
    public static readonly string[] CommonRemaps =
    [
        "va_list=void*",
        "unsigned long=System.Runtime.InteropServices.CULong",
        "FILE=void",
        "_iobuf=void",
        "_IO_FILE=void",
    ];

    // Macros that expand to compound literals or other expressions ClangSharp cannot lower; each has
    // a hand-written equivalent in src/FFmpeg.Interop.
    //
    // FF_API_* are FFmpeg's internal deprecation switches, not API. AV_CH_* are legacy channel masks
    // built by shifting by an enum value, which C# rejects; AVChannelLayout is the current API.
    // C variadic functions cannot be called with runtime marshalling disabled: format in managed code
    // and use avio_write, and read FFmpeg's log through av_log_set_callback.
    public static readonly string[] CommonExcludes =
    [
        "AV_TIME_BASE_Q",
        "AVStreamGroupLCEVC",
        "FF_API_*",
        "AV_CH_*",
        "AV_CHANNEL_LAYOUT_*",
        "av_log",
        "av_log_once",
        "avio_printf",
    ];

    // Calls that only read static tables or do integer arithmetic: they never block, allocate, take a
    // lock or call back into managed code, so they may skip the GC transition. Several sit on the per
    // frame and per packet path (timestamp rescaling, format lookups).
    public static readonly string[] NoGCTransition =
    [
        "avutil_version",
        "avcodec_version",
        "avformat_version",
        "avdevice_version",
        "swscale_version",
        "swresample_version",
        "av_rescale",
        "av_rescale_q",
        "av_rescale_rnd",
        "av_rescale_q_rnd",
        "av_compare_ts",
        "av_packet_rescale_ts",
        "av_get_bytes_per_sample",
        "av_sample_fmt_is_planar",
        "av_get_sample_fmt_name",
        "av_get_pix_fmt_name",
        "av_pix_fmt_desc_get",
        "av_pix_fmt_count_planes",
        "avcodec_get_name",
        "avcodec_get_type",
        "avcodec_descriptor_get",
        "av_hwdevice_get_type_name",
        "av_codec_is_encoder",
        "av_codec_is_decoder",
        "av_frame_is_writable",
        "av_buffer_is_writable",
    ];

    private const string Util = "ffmpeg:libavutil/";

    public static readonly IReadOnlyList<Pass> All =
    [
        new("helpers", "avutil", "LibAVUtilHelpers", Host.Windows, [], [], [], [], []),
        new(
            "avutil",
            "avutil",
            "LibAVUtil",
            Host.Windows,
            [
                "libavutil/avutil.h",
                "libavutil/buffer.h",
                "libavutil/channel_layout.h",
                "libavutil/cpu.h",
                "libavutil/dict.h",
                "libavutil/display.h",
                "libavutil/error.h",
                "libavutil/frame.h",
                "libavutil/hdr_dynamic_metadata.h",
                "libavutil/hwcontext.h",
                "libavutil/imgutils.h",
                "libavutil/log.h",
                "libavutil/mastering_display_metadata.h",
                "libavutil/mathematics.h",
                "libavutil/mem.h",
                "libavutil/opt.h",
                "libavutil/pixdesc.h",
                "libavutil/pixfmt.h",
                "libavutil/rational.h",
                "libavutil/samplefmt.h",
                "libavutil/time.h",
                "libavutil/version.h",
            ],
            [
                Util + "avutil.h",
                Util + "buffer.h",
                Util + "channel_layout.h",
                Util + "cpu.h",
                Util + "dict.h",
                Util + "display.h",
                Util + "error.h",
                Util + "frame.h",
                Util + "hdr_dynamic_metadata.h",
                Util + "hwcontext.h",
                Util + "imgutils.h",
                Util + "log.h",
                Util + "mastering_display_metadata.h",
                Util + "mathematics.h",
                Util + "mem.h",
                Util + "opt.h",
                Util + "pixdesc.h",
                Util + "pixfmt.h",
                Util + "rational.h",
                Util + "samplefmt.h",
                Util + "time.h",
                Util + "version.h",
            ],
            [],
            [],
            []
        ),
        Library(
            "avcodec",
            "LibAVCodec",
            [
                "avcodec.h",
                "bsf.h",
                "codec.h",
                "codec_desc.h",
                "codec_id.h",
                "codec_par.h",
                "defs.h",
                "packet.h",
                "version.h",
                "version_major.h",
            ]
        ),
        Library(
            "avformat",
            "LibAVFormat",
            ["avformat.h", "avio.h", "version.h", "version_major.h"],
            // An anonymous struct reached through a pointer field gets an invalid generated name.
            remaps: ["__AnonymousRecord_avformat_L989_C5=AVStreamGroupTileGridOffset"]
        ),
        Library("avdevice", "LibAVDevice", ["avdevice.h", "version.h", "version_major.h"]),
        Library("swscale", "LibSwScale", ["swscale.h", "version.h", "version_major.h"]),
        Library("swresample", "LibSwResample", ["swresample.h", "version.h", "version_major.h"]),
        // Only the version: libavfilter is not bound yet, but libavdevice links it, so the loader must load
        // and check it before libavdevice resolves.
        Library("avfilter", "LibAVFilter", ["version_major.h"]),
        // Hardware contexts: one pass per API, each traversing only its own hwcontext header. The
        // SDK types they mention stay opaque (remapped to void, so pointers become void*); a
        // consumer holds them as the handles the SDK's own bindings define.
        HwContext("hw_drm", "hwcontext_drm.h", []),
        HwContext("hw_vaapi", "hwcontext_vaapi.h", ["libva"], ["VASurfaceAttrib=void"]),
        VulkanContext(),
        HwContext(
            "hw_cuda",
            "hwcontext_cuda.h",
            ["nvcodec"],
            ["CUctx_st=void", "CUstream_st=void"],
            prelude: "ffnvcodec/dynlink_cuda.h"
        ),
        HwContext(
            "hw_d3d11va",
            "hwcontext_d3d11va.h",
            [],
            [
                "ID3D11Device=void",
                "ID3D11DeviceContext=void",
                "ID3D11VideoDevice=void",
                "ID3D11VideoContext=void",
                "ID3D11Texture2D=void",
            ]
        ),
        HwContext(
            "hw_d3d12va",
            "hwcontext_d3d12va.h",
            [],
            [
                "ID3D12Device=void",
                "ID3D12VideoDevice=void",
                "ID3D12Resource=void",
                "ID3D12Fence=void",
                "DXGI_FORMAT=int",
                "D3D12_RESOURCE_FLAGS=int",
                "D3D12_HEAP_FLAGS=int",
            ]
        ),
    ];

    // hwcontext_vulkan.h embeds Vulkan values (enums and VkPhysicalDeviceFeatures2 by value), which are
    // generated from the pinned Vulkan-Headers, restricted to the declarations
    // the context structs use. Vulkan handles stay opaque: on the 64-bit targets these bindings support,
    // dispatchable and non-dispatchable handles alike are pointers to incomplete structs.
    private static Pass VulkanContext() =>
        new(
            "hw_vulkan",
            "avutil",
            "LibAVUtil",
            Host.Windows,
            ["libavutil/hwcontext_vulkan.h"],
            ["ffmpeg:libavutil/hwcontext_vulkan.h", "vulkan:vulkan/vulkan_core.h"],
            ["vulkan"],
            [
                "VkInstance_T=void",
                "VkPhysicalDevice_T=void",
                "VkDevice_T=void",
                "VkImage_T=void",
                "VkSemaphore_T=void",
                "VkDeviceMemory_T=void",
                "VkAllocationCallbacks=void",
            ],
            []
        )
        {
            DeclarationFilter =
            [
                "AV*",
                "av_*",
                "VkPhysicalDeviceFeatures",
                "VkPhysicalDeviceFeatures2",
                "VkStructureType",
                "VkFormat",
                "VkImageTiling",
                "VkImageLayout",
                "VkQueueFlagBits",
                "VkMemoryPropertyFlagBits",
                "VkImageUsageFlagBits",
                "VkVideoCodecOperationFlagBitsKHR",
                // Identifying which GPU a Vulkan device is (its LUID and UUID).
                "VkPhysicalDeviceProperties2",
                "VkPhysicalDeviceProperties",
                "VkPhysicalDeviceLimits",
                "VkPhysicalDeviceSparseProperties",
                "VkPhysicalDeviceType",
                "VkPhysicalDeviceIDProperties",
            ],
        };

    private static Pass HwContext(
        string name,
        string header,
        string[] includeRoots,
        string[]? remaps = null,
        string? prelude = null
    ) =>
        new(
            name,
            "avutil",
            "LibAVUtil",
            Host.Windows,
            [.. (prelude is null ? [] : new[] { prelude }), $"libavutil/{header}"],
            [$"ffmpeg:libavutil/{header}"],
            includeRoots,
            remaps ?? [],
            []
        );

    private static Pass Library(
        string library,
        string className,
        string[] headers,
        string[]? remaps = null
    ) =>
        new(
            library,
            library,
            className,
            Host.Windows,
            [.. headers.Select(h => $"lib{library}/{h}")],
            [.. headers.Select(h => $"ffmpeg:lib{library}/{h}")],
            [],
            remaps ?? [],
            []
        );

    // Diagnostics that are expected on every run and carry no information: function-like macros
    // (hand-written where needed) and GCC attributes on inline functions.
    public static bool IsAllowedDiagnostic(string diagnostic) =>
        diagnostic.Contains("Function like macro definition", StringComparison.Ordinal)
        || diagnostic.Contains("Unsupported attribute", StringComparison.Ordinal);
}

internal partial class Program
{
    [GeneratedRegex(@"public (?:unsafe )?partial struct (\w+)\s*\{\s*\}")]
    private static partial Regex OpaqueStruct();

    // One generated test class, top-level or nested, from its summary line to the brace that closes it
    // at the same indentation.
    [GeneratedRegex(
        @"^(?<indent>[ ]*)/// <summary>Provides validation of the <see cref=""(?<name>\w+)"" /> struct\.</summary>\r?\n.*?^\k<indent>\}\r?\n\r?\n?",
        RegexOptions.Multiline | RegexOptions.Singleline
    )]
    private static partial Regex TestClass();
}
